import axios from 'axios';
import { ModelProvider, Message } from '../store/useAppStore';

// Safety: API keys should be provided via secure environment variables (.env)
const GROQ_API_KEY = process.env.EXPO_PUBLIC_GROQ_API_KEY || 'MISSING_KEY';
const OPENROUTER_API_KEY = process.env.EXPO_PUBLIC_OPENROUTER_API_KEY || 'MISSING_KEY';

/**
 * ARCHITECTURAL NOTE:
 * In a full production build, these endpoints would route to specialized
 * infrastructure for Image, Video, and Audio generation (e.g., Fal.ai, Replicate, Suno API).
 * In this MVP, we simulate the media return or route via multimodal text-to-media bridges.
 */

export const generateResponse = async (
  model: ModelProvider,
  messages: Message[]
): Promise<string> => {
  if (GROQ_API_KEY === 'MISSING_KEY' || OPENROUTER_API_KEY === 'MISSING_KEY') {
      return "Configuration Error: API Keys are missing. Please add them to your .env file.";
  }

  const lastUserMsg = messages.filter(m => m.role === 'user').pop()?.content || "";

  // Handle Specialized Media Categories
  if (model.category === 'image') {
     return `![Generated Image](${await simulateImageGen(lastUserMsg, model.id)})`;
  }

  if (model.category === 'video') {
     return `🎥 [Spatial Video Generated by ${model.name}] for prompt: "${lastUserMsg}"`;
  }

  if (model.category === 'music') {
     return `🎵 [Audio Segment Synthesized by ${model.name}] (Duration: 0:30)`;
  }

  // Standard Text/Coding Categories
  const formattedMessages = messages.map(m => ({
    role: m.role,
    content: m.content
  }));

  try {
    if (model.routingKey && (model.routingKey.includes('llama') || model.routingKey.includes('gemma') || model.routingKey.includes('mistral'))) {
       const response = await axios.post('https://api.groq.com/openai/v1/chat/completions', {
          model: model.routingKey,
          messages: formattedMessages,
       }, {
          headers: {
             'Authorization': `Bearer ${GROQ_API_KEY}`,
             'Content-Type': 'application/json'
          }
       });
       return response.data.choices[0].message.content;
    } else {
       const response = await axios.post('https://openrouter.ai/api/v1/chat/completions', {
          model: model.routingKey || 'openai/gpt-3.5-turbo',
          messages: formattedMessages,
       }, {
          headers: {
             'Authorization': `Bearer ${OPENROUTER_API_KEY}`,
             'Content-Type': 'application/json',
             'HTTP-Referer': 'https://ai-spatial-console.app',
             'X-Title': 'AI Spatial Console',
          }
       });
       return response.data.choices[0].message.content;
    }
  } catch (error) {
    console.error('API Error:', error);
    return "Error: Could not reach the model server. Please check your connectivity and API keys.";
  }
};

/**
 * Simulates a realistic Image Generation delay and returns a placeholder.
 * In production, replace with Fal.ai or DALL-E API calls.
 */
async function simulateImageGen(prompt: string, modelId: string): Promise<string> {
   await new Promise(resolve => setTimeout(resolve, 3000)); // Simulate diffusion time
   return `https://picsum.photos/seed/${modelId + prompt.length}/1024/1024`;
}
