import React, { useState } from 'react';
import { StyleSheet, View, Text, TouchableOpacity, ScrollView, SafeAreaView, Dimensions } from 'react-native';
import { useAppStore } from '../store/useAppStore';
import { Calendar, ChevronLeft as CalLeft, ChevronRight as CalRight } from 'lucide-react-native';
import { X, Brain, FolderOpen, CheckSquare, Bell, Code, Plus } from 'lucide-react-native';
import Animated, { useAnimatedStyle, withSpring, useSharedValue } from 'react-native-reanimated';

type ToolTab = 'Memories' | 'Projects' | 'Tasks' | 'Reminders' | 'Artifacts';

const SCREEN_WIDTH = Dimensions.get('window').width;

// Define specific mock data structure based on tool type to simulate auto-generation


export const SmartGenSuiteView: React.FC = () => {
  const { isSmartGenOpen, setSmartGenOpen } = useAppStore();
  const [activeTab, setActiveTab] = useState<ToolTab>('Memories');

  // Animated sliding value
  const translateX = useSharedValue(SCREEN_WIDTH);

  React.useEffect(() => {
    if (isSmartGenOpen) {
      translateX.value = withSpring(0, { mass: 0.8, damping: 15, stiffness: 100 });
    } else {
      translateX.value = withSpring(SCREEN_WIDTH, { mass: 0.8, damping: 15, stiffness: 100 });
    }
  }, [isSmartGenOpen, translateX]);

  const animatedStyle = useAnimatedStyle(() => {
    return {
      transform: [{ translateX: translateX.value }],
    };
  });

  const tabs: { id: ToolTab, icon: any }[] = [
     { id: 'Memories', icon: Brain },
     { id: 'Projects', icon: FolderOpen },
     { id: 'Tasks', icon: CheckSquare },
     { id: 'Reminders', icon: Bell },
     { id: 'Artifacts', icon: Code },
  ];

  return (
    <Animated.View style={[styles.container, animatedStyle]} pointerEvents={isSmartGenOpen ? "auto" : "none"}>
      <SafeAreaView style={styles.safeArea}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.headerTitle}>SMART GEN SUITE</Text>
          <TouchableOpacity onPress={() => setSmartGenOpen(false)}>
            <X color="#fff" size={24} />
          </TouchableOpacity>
        </View>

        <View style={styles.content}>
           {/* Sidebar Tabs */}
           <View style={styles.sidebar}>
              {tabs.map(tab => {
                 const Icon = tab.icon;
                 const isActive = activeTab === tab.id;
                 return (
                    <TouchableOpacity
                       key={tab.id}
                       style={[styles.tabButton, isActive && styles.tabButtonActive]}
                       onPress={() => setActiveTab(tab.id)}
                    >
                       <Icon color={isActive ? "#fff" : "rgba(255,255,255,0.4)"} size={24} />
                       {isActive && <View style={styles.activeIndicator} />}
                    </TouchableOpacity>
                 );
              })}
           </View>

           {/* Main Content Area */}
           <View style={styles.mainArea}>
              <View style={styles.areaHeader}>
                <Text style={styles.areaTitle}>{activeTab.toUpperCase()}</Text>
                <TouchableOpacity style={styles.addBtn}>
                  <Plus color="#fff" size={20} />
                </TouchableOpacity>
              </View>



              <View style={styles.footerNote}>
                 <Text style={styles.footerText}>
                    *Smart Gen Suite items are autogenerated (auto-named, auto-tagged) based on context derived from all non-private mode inputs, including conversation history, files, and other generated tools.
                 </Text>
              </View>
           </View>
        </View>
      </SafeAreaView>
    </Animated.View>
  );
};

const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(10,10,12,0.98)',
    zIndex: 100,
    elevation: 100,
    flexDirection: 'row',
  },
  safeArea: {
    flex: 1,
  },
  content: {
    flex: 1,
    flexDirection: 'row',
  },
  sidebar: {
    width: 80,
    backgroundColor: 'rgba(255,255,255,0.02)',
    borderRightWidth: 1,
    borderRightColor: 'rgba(255,255,255,0.05)',
    paddingTop: 40,
    alignItems: 'center',
    gap: 20,
  },
  tabButton: {
    padding: 10,
    borderRadius: 20,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabButtonActive: {
    backgroundColor: 'rgba(66, 133, 244, 0.2)',
  },
  activeIndicator: {
    position: 'absolute',
    left: 0,
    top: '25%',
    bottom: '25%',
    width: 3,
    backgroundColor: '#4285F4',
    borderTopRightRadius: 3,
    borderBottomRightRadius: 3,
  },
  mainArea: {
    flex: 1,
    padding: 20,
  },
  areaHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  areaTitle: {
    color: '#fff',
    fontSize: 24,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  headerTitle: {
    color: '#fff',
    fontSize: 24,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  addBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 20,
    gap: 5,
  },
  list: {
    flex: 1,
  },
  listContent: {
    paddingBottom: 40,
  },
  listContainer: {
    flex: 1,
  },
  entryCard: {
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderRadius: 16,
    padding: 15,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
  },
  itemCard: {
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderRadius: 16,
    padding: 15,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
  },
  entryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  itemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  entryTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    flex: 1,
    marginRight: 10,
  },
  itemTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    flex: 1,
    marginRight: 10,
  },
  entryTime: {
    color: 'rgba(255,255,255,0.4)',
    fontSize: 12,
  },
  entryText: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 12,
  },
  itemDesc: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 12,
  },
  badgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  itemBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.1)',
    color: '#fff',
    fontSize: 10,
    fontWeight: '700',
    overflow: 'hidden',
  },
  badgeText: {
    fontSize: 10,
    fontWeight: '700',
  },
  footerNote: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 15,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.05)',
    gap: 8,
  },
  footerText: {
    color: 'rgba(255,255,255,0.3)',
    fontSize: 12,
    fontStyle: 'italic',
  },
  calendarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 15,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 16,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  calendarMonth: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  calDayHeader: {
    width: '14.28%',
    textAlign: 'center',
    color: 'rgba(255,255,255,0.4)',
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 10,
  },
  calCell: {
    width: '14.28%',
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  calCellToday: {
    backgroundColor: 'rgba(66, 133, 244, 0.2)',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#4285F4',
  },
  calCellText: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 14,
  },
  calCellTextToday: {
    color: '#fff',
    fontWeight: '800',
  },
  calEventDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#ff453a',
    marginTop: 2,
  },
  emptyText: {
    color: 'rgba(255,255,255,0.4)',
    textAlign: 'center',
    marginTop: 40,
    fontSize: 14,
  },
  itemMeta: {
    color: 'rgba(255,255,255,0.4)',
    fontSize: 12,
    marginTop: 8,
  }
});