import React, { useState } from 'react';
import { StyleSheet, View, Text, TouchableOpacity, ScrollView, SafeAreaView, Dimensions } from 'react-native';
import { useAppStore } from '../store/useAppStore';
import { X, Brain, FolderOpen, CheckSquare, Bell, Code, Plus } from 'lucide-react-native';
import Animated, { useAnimatedStyle, withSpring, useSharedValue } from 'react-native-reanimated';

type ToolTab = 'Memories' | 'Projects' | 'Tasks' | 'Reminders' | 'Artifacts';

const SCREEN_WIDTH = Dimensions.get('window').width;

export const SmartGenSuiteView: React.FC = () => {
  const { isSmartGenOpen, setSmartGenOpen } = useAppStore();
  const [activeTab, setActiveTab] = useState<ToolTab>('Memories');

  // Animated sliding value
  const translateX = useSharedValue(SCREEN_WIDTH);

  React.useEffect(() => {
    if (isSmartGenOpen) {
      translateX.value = withSpring(0, { mass: 0.8, damping: 15, stiffness: 100 });
    } else {
      translateX.value = withSpring(SCREEN_WIDTH, { mass: 0.8, damping: 15, stiffness: 100 });
    }
  }, [isSmartGenOpen, translateX]);

  const animatedStyle = useAnimatedStyle(() => {
    return {
      transform: [{ translateX: translateX.value }],
    };
  });

  const tabs: { id: ToolTab, icon: any }[] = [
     { id: 'Memories', icon: Brain },
     { id: 'Projects', icon: FolderOpen },
     { id: 'Tasks', icon: CheckSquare },
     { id: 'Reminders', icon: Bell },
     { id: 'Artifacts', icon: Code },
  ];

  return (
    <Animated.View style={[styles.container, animatedStyle]} pointerEvents={isSmartGenOpen ? "auto" : "none"}>
      <SafeAreaView style={styles.safeArea}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.headerTitle}>SMART GEN SUITE</Text>
          <TouchableOpacity onPress={() => setSmartGenOpen(false)}>
            <X color="#fff" size={24} />
          </TouchableOpacity>
        </View>

        <View style={styles.content}>
           {/* Sidebar Tabs */}
           <View style={styles.sidebar}>
              {tabs.map(tab => {
                 const Icon = tab.icon;
                 const isActive = activeTab === tab.id;
                 return (
                    <TouchableOpacity
                       key={tab.id}
                       style={[styles.tabButton, isActive && styles.tabButtonActive]}
                       onPress={() => setActiveTab(tab.id)}
                    >
                       <Icon color={isActive ? "#fff" : "rgba(255,255,255,0.4)"} size={24} />
                       {isActive && <View style={styles.activeIndicator} />}
                    </TouchableOpacity>
                 );
              })}
           </View>

           {/* Main Content Area */}
           <View style={styles.mainArea}>
              <View style={styles.areaHeader}>
                <Text style={styles.areaTitle}>{activeTab.toUpperCase()}</Text>
                <TouchableOpacity style={styles.addBtn}>
                  <Plus color="#fff" size={20} />
                </TouchableOpacity>
              </View>

              <ScrollView style={styles.list} contentContainerStyle={styles.listContent}>
                 {/* Mock Data Entries with 3D Depth Feel */}
                 {[1, 2, 3].map(i => (
                   <View key={i} style={styles.entryCard}>
                      <View style={styles.entryHeader}>
                        <Text style={styles.entryTitle}>Autogenerated {activeTab} #{i}</Text>
                        <Text style={styles.entryTime}>2h ago</Text>
                      </View>
                      <Text style={styles.entryText}>
                         Derived from contextual cues across multiple models based on recent multi-turn analysis.
                      </Text>
                      <View style={styles.badgeRow}>
                         <View style={styles.badge}>
                            <Text style={styles.badgeText}>Auto-Gen</Text>
                         </View>
                         <View style={[styles.badge, { backgroundColor: 'rgba(66, 133, 244, 0.2)' }]}>
                            <Text style={[styles.badgeText, { color: '#4285F4' }]}>Cross-Model</Text>
                         </View>
                      </View>
                   </View>
                 ))}
              </ScrollView>

              <View style={styles.footerNote}>
                 <Text style={styles.footerText}>
                    *Smart Gen Suite items are autogenerated based on contextual cues from conversation history. Use the Marketplace to expand logic.
                 </Text>
              </View>
           </View>
        </View>
      </SafeAreaView>
    </Animated.View>
  );
};

const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(15,15,18,0.98)', // Deep slate with high opacity
    zIndex: 150,
  },
  safeArea: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.1)',
  },
  headerTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 2,
  },
  content: {
    flex: 1,
    flexDirection: 'row',
  },
  sidebar: {
    width: 70,
    borderRightWidth: 1,
    borderRightColor: 'rgba(255,255,255,0.05)',
    alignItems: 'center',
    paddingTop: 20,
    gap: 25,
    backgroundColor: 'rgba(0,0,0,0.2)',
  },
  tabButton: {
     padding: 12,
     position: 'relative',
  },
  tabButtonActive: {
     backgroundColor: 'rgba(255,255,255,0.08)',
     borderRadius: 12,
  },
  activeIndicator: {
    position: 'absolute',
    left: -10,
    top: 10,
    bottom: 10,
    width: 3,
    backgroundColor: '#fff',
    borderRadius: 3,
  },
  mainArea: {
    flex: 1,
    padding: 20,
  },
  areaHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  areaTitle: {
    color: '#fff',
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: 1,
  },
  addBtn: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    padding: 8,
    borderRadius: 20,
  },
  list: {
    flex: 1,
  },
  listContent: {
    gap: 15,
    paddingBottom: 20,
  },
  entryCard: {
     backgroundColor: 'rgba(255,255,255,0.03)',
     padding: 18,
     borderRadius: 16,
     borderWidth: 1,
     borderColor: 'rgba(255,255,255,0.08)',
     shadowColor: '#000',
     shadowOffset: { width: 0, height: 4 },
     shadowOpacity: 0.3,
     shadowRadius: 10,
  },
  entryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  entryTitle: {
     color: '#fff',
     fontSize: 16,
     fontWeight: '700',
  },
  entryTime: {
     color: 'rgba(255,255,255,0.4)',
     fontSize: 12,
  },
  entryText: {
     color: 'rgba(255,255,255,0.6)',
     fontSize: 14,
     lineHeight: 20,
     marginBottom: 15,
  },
  badgeRow: {
     flexDirection: 'row',
     gap: 10,
  },
  badge: {
     backgroundColor: 'rgba(255,255,255,0.08)',
     paddingHorizontal: 10,
     paddingVertical: 4,
     borderRadius: 12,
     borderWidth: 1,
     borderColor: 'rgba(255,255,255,0.05)',
  },
  badgeText: {
     color: 'rgba(255,255,255,0.7)',
     fontSize: 11,
     fontWeight: '600',
  },
  footerNote: {
     marginTop: 20,
     paddingTop: 15,
     borderTopWidth: 1,
     borderTopColor: 'rgba(255,255,255,0.1)',
  },
  footerText: {
     color: 'rgba(255,255,255,0.3)',
     fontSize: 11,
     fontStyle: 'italic',
     lineHeight: 16,
  }
});
