import React, { useState } from 'react';
import { StyleSheet, View, Text, TouchableOpacity, ScrollView, SafeAreaView } from 'react-native';
import { useAppStore } from '../store/useAppStore';
import { X, Brain, FolderOpen, CheckSquare, Bell, Code } from 'lucide-react-native';

type ToolTab = 'Memories' | 'Projects' | 'Tasks' | 'Reminders' | 'Artifacts';

export const SmartGenTools: React.FC = () => {
  const { isSmartGenOpen, setSmartGenOpen } = useAppStore();
  const [activeTab, setActiveTab] = useState<ToolTab>('Memories');

  if (!isSmartGenOpen) return null;

  const tabs: { id: ToolTab, icon: any }[] = [
     { id: 'Memories', icon: Brain },
     { id: 'Projects', icon: FolderOpen },
     { id: 'Tasks', icon: CheckSquare },
     { id: 'Reminders', icon: Bell },
     { id: 'Artifacts', icon: Code },
  ];

  return (
    <SafeAreaView style={styles.container}>
      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.headerTitle}>SMART GEN SUITE</Text>
        <TouchableOpacity onPress={() => setSmartGenOpen(false)}>
          <X color="#fff" size={24} />
        </TouchableOpacity>
      </View>

      <View style={styles.content}>
         {/* Sidebar Tabs */}
         <View style={styles.sidebar}>
            {tabs.map(tab => {
               const Icon = tab.icon;
               const isActive = activeTab === tab.id;
               return (
                  <TouchableOpacity
                     key={tab.id}
                     style={[styles.tabButton, isActive && styles.tabButtonActive]}
                     onPress={() => setActiveTab(tab.id)}
                  >
                     <Icon color={isActive ? "#fff" : "rgba(255,255,255,0.4)"} size={24} />
                  </TouchableOpacity>
               );
            })}
         </View>

         {/* Main Content Area */}
         <View style={styles.mainArea}>
            <Text style={styles.areaTitle}>{activeTab.toUpperCase()}</Text>

            <ScrollView style={styles.list}>
               {/* Mock Data Entry */}
               <View style={styles.entryCard}>
                  <Text style={styles.entryTitle}>Auto-Generated {activeTab} Entry</Text>
                  <Text style={styles.entryText}>
                     Derived from contextual cues across all non-private conversations.
                  </Text>
                  <View style={styles.badgeRow}>
                     <View style={styles.badge}>
                        <Text style={styles.badgeText}>GPT-4o</Text>
                     </View>
                     <View style={styles.badge}>
                        <Text style={styles.badgeText}>System</Text>
                     </View>
                  </View>
               </View>
            </ScrollView>

            <View style={styles.footerNote}>
               <Text style={styles.footerText}>
                  *Smart Gen Suite items are autogenerated based on contextual cues from conversation history.
               </Text>
            </View>
         </View>
      </View>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(20,20,20,0.98)',
    zIndex: 150,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.1)',
  },
  headerTitle: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 2,
  },
  content: {
    flex: 1,
    flexDirection: 'row',
  },
  sidebar: {
    width: 60,
    borderRightWidth: 1,
    borderRightColor: 'rgba(255,255,255,0.1)',
    alignItems: 'center',
    paddingTop: 20,
    gap: 30,
  },
  tabButton: {
     padding: 10,
  },
  tabButtonActive: {
     backgroundColor: 'rgba(255,255,255,0.1)',
     borderRadius: 10,
  },
  mainArea: {
    flex: 1,
    padding: 20,
  },
  areaTitle: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 20,
    letterSpacing: 1,
  },
  list: {
    flex: 1,
  },
  entryCard: {
     backgroundColor: 'rgba(255,255,255,0.05)',
     padding: 15,
     borderRadius: 12,
     borderWidth: 1,
     borderColor: 'rgba(255,255,255,0.1)',
  },
  entryTitle: {
     color: '#fff',
     fontSize: 16,
     fontWeight: '600',
     marginBottom: 5,
  },
  entryText: {
     color: 'rgba(255,255,255,0.6)',
     fontSize: 14,
     marginBottom: 15,
  },
  badgeRow: {
     flexDirection: 'row',
     gap: 10,
  },
  badge: {
     backgroundColor: 'rgba(255,255,255,0.1)',
     paddingHorizontal: 10,
     paddingVertical: 4,
     borderRadius: 10,
  },
  badgeText: {
     color: '#fff',
     fontSize: 10,
     fontWeight: '600',
  },
  footerNote: {
     marginTop: 20,
     paddingTop: 15,
     borderTopWidth: 1,
     borderTopColor: 'rgba(255,255,255,0.1)',
  },
  footerText: {
     color: 'rgba(255,255,255,0.3)',
     fontSize: 10,
     fontStyle: 'italic',
  }
});
